openapi: "3.0.0"
info:
  version: 4.0.2
  title: Orders
  description: |
    * TODO
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: todo
    email: mailing-list@tbd.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://placeholderdomain.io

paths: {} # no paths

components:
  schemas:
    enumerateOrdersResponse:
      required:
        - ordersCollection
      description: Collection of orders to return to the UI
      properties:
        ordersCollection:
          type: array
          items:
            $ref: 'commonSchemas.yaml#/components/schemas/encodededPayloadWrapper'

    enumerateOrdersQuery:
      description: Query parameters for requesting a collection of orders
      required:
        - CommonPayloadHeader
        - startDate
        - endDate
        - limitCount
      properties:
        CommonPayloadHeader:
          $ref: 'commonSchemas.yaml#/components/schemas/commonPayloadHeader'
        startDate:
          description: Start date of the range
          type: string
          format: date-time
        endDate:
          description: End date of the range
          type: string
          format: date-time
        limitCount: 
          description: Max number of items to return
          type: integer #TODO any constraints on this?
          format: int32