openapi: "3.0.0"

components:
 securitySchemes:
    bearerAuth: 
      type: http
      scheme: bearer
      bearerFormat: JWT 
security:
  - bearerAuth: []

info:
  version: 4.0.9
  title: Orders
  description: |
    * TODO
  termsOfService: http://placeholderdomain.io/terms/
  contact:
    name: todo
    email: mailing-list@tbd.com
    url: http://placeholderdomain.io
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - url: http://placeholderdomain.io

paths:
  /v1/orders/enumerate:
    post:
      summary: Enumerate Orders
      description: Request a collection of orders matching the provided query parameters
      operationId: enumerateOrders
      requestBody:
        description: EnumerateOrders
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/ordersSchemas.yaml#/components/schemas/enumerateOrdersQuery'
      responses:
        '202':
          description: Request processed successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/ordersSchemas.yaml#/components/schemas/enumerateOrdersResponse'
        default:
          description: Unexpected error occured
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'

  /v1/orders/create:
    post:
      summary: Create an Order
      description: Create an Order
      operationId: createOrder
      requestBody:
        description: createOrder
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/commonSchemas.yaml#/components/schemas/encodededPayloadWrapper'
      responses:
        '202':
          description: Request processed successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/acceptedResponse'
        default:
          description: Unexpected error occured
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'

  /v1/orders/cancel/{sgsOrderId}:
    put:
      summary: Cancel an Order
      description: Cancel an Order
      operationId: cancelOrder
      parameters:
        - name: sgsOrderId
          in: path
          description: The SGS Order Id
          required: true
      requestBody:
        description: cancelOrder
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/commonSchemas.yaml#/components/schemas/encodededPayloadWrapper'
      responses:
        '202':
          description: Request processed successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/acceptedResponse'
        default:
          description: Unexpected error occured
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'

  /v1/orders/revise/{sgsOrderId}:
    put:
      summary: Revise an Order
      description: Revise an order
      operationId: reviseOrder
      parameters:
        - name: sgsOrderId
          in: path
          description: The SGS Order Id
          required: true
      requestBody:
        description: reviseOrder
        required: true
        content:
          application/json:
            schema:
              $ref: 'schemas/commonSchemas.yaml#/components/schemas/encodededPayloadWrapper'
      responses:
        '202':
          description: Request processed successfully
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/acceptedResponse'
        default:
          description: Unexpected error occured
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'

  /v1/orders/acknowledge:
      post:
        summary: Acknowledgement of order processing
        description: Acknowledgement of order processing
        operationId: acknowledgeOrder
        requestBody:
          description: acknowledge 
          required: true
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/encodededPayloadWrapper'
        responses:
          '200':
            description: Request processed successfully
            content:
              application/json:
                schema:
                  $ref: 'schemas/commonSchemas.yaml#/components/schemas/acceptedResponse'
          default:
            description: Unexpected error occured
            content:
              application/json:
                schema:
                  $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'

  /v1/orders/approve/{sgsOrderId}:
      post:
        summary: Receive events from SGS for accepted updates to an order
        description: Receive events for from SGS for accepted updates to an order
        operationId: approveOrder
        parameters:
          - name: sgsOrderId
            in: path
            description: The SGS Order Id
            required: true
        requestBody:
          description: reviseOrder
          required: true
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/encodededPayloadWrapper'
        responses:
          '202':
            description: Request processed successfully
            content:
              application/json:
                schema:
                  $ref: 'schemas/commonSchemas.yaml#/components/schemas/acceptedResponse'
          default:
            description: Unexpected error occured
            content:
              application/json:
                schema:
                  $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'

  /v1/orders/confirm/{sgsOrderId}:
      post:
        summary: Confirm an Order
        description: Confirm an Order
        operationId: confirmOrder
        parameters:
          - name: sgsOrderId
            in: path
            description: The SGS Order Id
            required: true
        requestBody:
          description: reviseOrder
          required: true
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/encodededPayloadWrapper'
        responses:
          '202':
            description: Request processed successfully
            content:
              application/json:
                schema:
                  $ref: 'schemas/commonSchemas.yaml#/components/schemas/acceptedResponse'
          default:
            description: Unexpected error occured
            content:
              application/json:
                schema:
                  $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'

  /v1/orders/notifyOpen/{sgsOrderId}:
      post:
        summary: Notify on Open Order
        description: Notify on Open Order
        operationId: notifyOpenOrder
        parameters:
          - name: sgsOrderId
            in: path
            description: The SGS Order Id
            required: true
        requestBody:
          description: reviseOrder
          required: true
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/encodededPayloadWrapper'
        responses:
          '202':
            description: Request processed successfully
            content:
              application/json:
                schema:
                  $ref: 'schemas/commonSchemas.yaml#/components/schemas/acceptedResponse'
          default:
            description: Unexpected error occured
            content:
              application/json:
                schema:
                  $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'

  /v1/orders/reject/{sgsOrderId}:
      post:
        summary: Receive events from SGS for rejected updates to an order
        description: Receive events from SGS for rejected updates to an order
        operationId: rejectOrder
        parameters:
          - name: sgsOrderId
            in: path
            description: The SGS Order Id
            required: true
        requestBody:
          description: reviseOrder
          required: true
          content:
            application/json:
              schema:
                $ref: 'schemas/commonSchemas.yaml#/components/schemas/encodededPayloadWrapper'
        responses:
          '202':
            description: Request processed successfully
            content:
              application/json:
                schema:
                  $ref: 'schemas/commonSchemas.yaml#/components/schemas/acceptedResponse'
          default:
            description: Unexpected error occured
            content:
              application/json:
                schema:
                  $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
          
  /v1/orders/subscriptions:
      post:
          summary: Create a new subscription
          description: Create a new subscription
          operationId: ordersSubscription
          requestBody:
            description: Create a new subscription
            required: true
            content:
              application/json:
                schema:
                  $ref: 'schemas/commonSchemas.yaml#/components/schemas/subscriptionRequest'
          responses:
            '201':
              description: Request processed successfully
              content:
                application/json:
                  schema:
                    $ref: 'schemas/commonSchemas.yaml#/components/schemas/subscriptionResponse'
            default:
              description: Unexpected error occured
              content:
                application/json:
                  schema:
                    $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'

  /v1/orders/subscriptions/{id}:
      delete:
        summary: Remove a subscription
        description: Existing subscriptions can be deleted by making a DELETE request against the subscription resource
        operationId: Remove a subscription
        parameters:
        - name: id
          in: path
          description: The subscription id
          required: true
        responses:
          '204':
            description: Subscription deleted
          default:
            description: Unexpected error occured
            content:
              application/json:
                schema:
                  $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
      
      get:
        summary: Enumerating subscriptions
        description: Get a list of active subscriptions
        operationId: Enumerating subscriptions
        parameters:
        - name: id
          in: path
          description: The subscription id
          required: true
        responses:
          '200':
            description: Request processed successfully
            content:
              application/json:
                schema:
                  $ref: 'schemas/commonSchemas.yaml#/components/schemas/enumerateSubscriptions'
          default:
            description: Unexpected error occured
            content:
              application/json:
                schema:
                  $ref: 'schemas/commonSchemas.yaml#/components/schemas/Error'
